- src/components/browse/components/StackedBlockTable.js
**Problem:** Quality Metrics Summary table display ellipsis for long header columns (and also browser's built-in tooltip not working on mouse hover) - https://data.4dnucleome.org/experiment-set-replicates/4DNESDG4HNP9/
**Solution:** A minor fix: data-tip attribute addded `data-tip={visibleTitle}`
**Improvement:** Tooltip is shown even if the column header is fully visible, since the ellipsis is displayed by browser vis the css `text-overflow: ellipsis` rule. Prevent tooltip for fully visible column headers is a nice to have.
> Minor fix to show tooltip over QMS tables column headers

- es/components/browse/SearchView.js
- es/components/browse/components/SearchResultTable.js
- es/components/forms/SubmissionView.js
- es/components/forms/components/submission-fields.js
- src/components/browse/SearchView.js
- src/components/browse/components/SearchResultTable.js
- src/components/forms/SubmissionView.js
- src/components/forms/components/submission-fields.js
**Note:** this PR should be handled with PR https://github.com/4dn-dcic/fourfront/pull/1174
1. Single selection's UI is changed, so both `multi select` and `single select` popup UIs are alike.
2. `SubmissionView` is updated to open `multi` or `single selection` popup according to the field type.
> Single Item Selection & SubmissionView Changes

- es/components/browse/components/FacetList/FacetOfFacets.js
- es/components/browse/components/FacetList/FacetTermsList.js
- es/components/browse/components/FacetList/RangeFacet.js
- es/components/browse/components/FacetList/TermsFacet.js
- es/components/browse/components/FacetList/index.js
- scss/facet-list.scss
- src/components/browse/components/FacetList/FacetOfFacets.js
- src/components/browse/components/FacetList/FacetTermsList.js
- src/components/browse/components/FacetList/RangeFacet.js
- src/components/browse/components/FacetList/TermsFacet.js
- src/components/browse/components/FacetList/index.js
Not sure if we should wait to merge this in or not; have the final schema decisions for grouping been officially made? Definitely needs testing on 4DN either way. And need to pull in changes from master (I'm having trouble getting new master on shared-portal-components working on my local).
Also, please take a look what I did with `mergeTerms()` and `anyTermsSelected()` in `index.js`. I pulled those methods out of `FacetTermsList` to make the indicator color and selected terms tooltips work in `FacetOfFacets`. Not sure if I should rework `FacetTermsList` to work the same way or not.
> Facet grouping

- es/components/forms/components/submission-fields.js
- src/components/forms/components/submission-fields.js
**Problem:**
- If a property is defined as enum in schema
and
- its value type is not string
then submission view fails while validating the submitted enum value, since it is recognized as string. This problem occurred while submitting a page with redirection. Page.json's related property is:
```
"code" : {
"title" : "Response Code",
"description" : "Code returned by response.",
"comment" : "See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection",
"type" : "integer",
"default" : 307,
"enum" : [301, 302, 303, 307]
}
```
**Solution:**
The value is converted to the schema-defined data type before validation/submission. (currently supports integer, float, number and boolean.)
> Fix of Enum Fields in Submission View Page

- es/components/browse/components/FacetList/FacetOfFacets.js
- es/components/browse/components/FacetList/FacetTermsList.js
- es/components/browse/components/FacetList/RangeFacet.js
- es/components/browse/components/FacetList/TermsFacet.js
- es/components/browse/components/FacetList/index.js
- es/components/browse/components/table-commons.js
- es/components/ui/PartialList.js
- scss/facet-list.scss
- src/components/browse/components/FacetList/FacetOfFacets.js
- src/components/browse/components/FacetList/FacetTermsList.js
- src/components/browse/components/FacetList/RangeFacet.js
- src/components/browse/components/FacetList/TermsFacet.js
- src/components/browse/components/FacetList/index.js
- src/components/browse/components/table-commons.js
- src/components/ui/PartialList.js
Selected terms are now always visible, even if facet is collapsed per UX research / design / recommendations from Shannon.
- If all terms are selected, no option to collapse until deselect term(s).
- For simpler transitions, active (selected or omitted) terms are grouped at top of list now.
Also, minor fixes UI/styling edits esp re: new UX changes.
Most notably, for "Common Properties", no terms get moved down there unless no filter set for that field at all anywhere. This gives a more much predictable experience without selected filters (often unexpectedly) jumping down into "common properties".
Selected (and/or Omitted) terms now always show up the same - as highlighted bar(s) - even if facet containing the term is collapsed. Gives a large quick overview of currently-active filters. …
> FacetList Updates re: UX -

- es/components/forms/components/SearchAsYouTypeLocal.js
- src/components/forms/components/SearchAsYouTypeLocal.js
Stops crashing on Page edits with `suggested_enum`/`enum` fields of type `integer`.
> hotfix: cast all values to string before filtering

- es/components/forms/components/LinkToDropdown.js
- es/components/forms/components/SearchAsYouTypeAjax.js
- es/components/forms/components/SearchSelectionMenu.js
- src/components/forms/components/LinkToDropdown.js
- src/components/forms/components/SearchAsYouTypeAjax.js
- src/components/forms/components/SearchSelectionMenu.js
**Testing Notes**
- Must be tested with [this branch](https://github.com/dbmi-bgm/cgap-portal/pull/91) on CGAP; otherwise cohort submission page will crash.
**Changelog**:
- Small changes to `<LinkToDropdown>` to make that component's search as you type setting easier to work with on cohort submission page.
- Added a toggle prop (boolean - `searchAsYouType`) to define whether or not search as you type is used in the dropdown. Defaults to what the statically fined check used to be.
- Made regex query case-insensitive for better matching.
- Swapped order of arguments in `<LinkToDropdown>` `onSelect()` methods to force compatibility with `<SearchAsYouTypeAjax>` `onChange()` in the case that it becomes necessary to swap them out in future.
- Chose to swap here, since it seemed to be connected …
> Fixes for cohort submissatajax

- es/components/browse/components/table-commons/ResultRowColumnBlockValue.js
- src/components/browse/components/table-commons/ResultRowColumnBlockValue.js
If have array of objects (linkTos) as value, then output array of link elements instead of ~ [Object object]. Should be self-explanatory from code. Output could look like, if change 4DN ExperimentSetTables.js defaultProps.columns `"experiments_in_set.biosample.biosource.individual.organism.name"` to `"experiments_in_set.biosample.biosource.individual.organism"`:
> Render linkTo Objects[] as link elements in table cells

- es/components/browse/SearchView.js
- es/components/browse/components/FacetList/FacetTermsList.js
- es/components/browse/components/FacetList/RangeFacet.js
- es/components/browse/components/FacetList/TermsFacet.js
- es/components/browse/components/FacetList/index.js
- es/components/browse/components/SearchResultTable.js
- es/components/browse/components/SelectedItemsController.js
- es/components/browse/components/above-table-controls/AboveSearchViewTableControls.js
- es/components/browse/components/table-commons/ColumnCombiner.js
- es/components/browse/components/table-commons/HeadersRow.js
- es/components/browse/components/table-commons/ResultRowColumnBlockValue.js
- es/components/browse/components/table-commons/basicColumnExtensionMap.js
- es/components/forms/SubmissionView.js
- es/components/forms/components/LinkToSelector.js
- es/components/forms/components/SearchAsYouTypeAjax.js
- es/components/forms/components/submission-fields.js
- es/components/static-pages/StaticPageBase.js
- es/components/ui/DropdownButton.js
- es/components/ui/ItemDetailList.js
- src/components/forms/SubmissionView.js
- src/components/forms/components/LinkToSelector.js
- src/components/forms/components/SearchAsYouTypeAjax.js
I ran into a bug in SubmissionView state that was causing the final create new linked object test in my SAYTAJAX cypress tests to fail. Apparently, we weren't checking/updating the validation state of the parent item anywhere upon submission of a newly created item. (I still sort of can't believe this? Was this maybe implemented at some point previously, and we accidentally deleted it? Or do you happen to know of something like this happening later in the flow of the 'create new linked item'-related methods?) 
Anyway, this resulted in there being occasions where the parent item had no more incomplete child objects, but was still unable to be validated (validate button disabled). So basically, I added a check before the state is set to see if the parent item's validation status would be …
> fix for findValidationState; update parent valid. state on obj submission

- es/components/util/file.js
- src/components/util/file.js
**First merge this PR, then release a new version. Then update SPC version of https://github.com/4dn-dcic/fourfront/pull/1368 and merge.**
`groupFilesByQCSummaryTitles` function used to sort the file's QCs by relevant schema's qc_order value. The implementation is moved to FF due to some FF-specific custom sorting.
> QC Sorting Removed

- es/components/util/object.js
- es/components/util/schema-transforms.js
- scss/facet-list.scss
- scss/search-view-table.scss
- src/components/util/object.js
- src/components/util/schema-transforms.js
Some small touchups & fixes that are needed for CGAP edits soon. Renamed SCSS variable used since removing $brand- variants (from old Bootstrap version) however the non brand- variants of color variables exist in both 4DN and CGAP now since both have been on Bootstrapv4 for some time now.
Will merge shortly, pls checkout/review if interested.
> Minor fix/touchup; comments.

- es/components/browse/EmbeddedSearchView.js
- es/components/browse/SearchView.js
- es/components/browse/components/ControlsAndResults.js
- es/components/browse/components/SearchResultTable.js
- es/components/browse/components/WindowNavigationController.js
- es/components/browse/components/table-commons/ColumnCombiner.js
- es/components/browse/components/table-commons/HeadersRow.js
- src/components/browse/EmbeddedSearchView.js
- src/components/browse/SearchView.js
- src/components/browse/components/ControlsAndResults.js
- src/components/browse/components/SearchResultTable.js
- src/components/browse/components/WindowNavigationController.js
- src/components/browse/components/table-commons/ColumnCombiner.js
- src/components/browse/components/table-commons/HeadersRow.js
- Remove support for `props.topLeftChildren` & `props.selectedFiles`
- Enable support for `props.aboveTableComponent`
- Enable support for `props.aboveFacetListComponent`
- Enable support for `props.detailPane`
- (Unlikely) Might consider removing `props.renderDetailPane` in future sometime in favor of just `detailPane`
> SearchView & Related: Enabling aboveTableComponent etc.

- es/components/browse/components/FacetList/RangeFacet.js
- es/components/browse/components/FacetList/index.js
- src/components/browse/components/FacetList/RangeFacet.js
Test with [cgap branch](https://github.com/dbmi-bgm/cgap-portal/pull/294).
Fix for double-parenthesis when label includes parenthetical.
- Simple check to see if label string includes an open parenthesis... if so, doesn't add another set. If it doesn't, it does. 
- So, most look the same, but facets like de Novo and Strand Fisher Score don't get duplicates.
Update Strand Fisher Score to use abbreviation.
- Added "abbreviation" for this field directly to `variantSample.json` schema facet definition... UI displays `facet.abbreviation` in `RangeClear` if present, and if not, uses facet display title.
Fix inclusivity bug/issue
- [Ranges are always inclusive on the lower bound and exclusive on the upper bound](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucke …
> Range facet demo updates

- es/components/browse/components/CustomColumnController.js
- es/components/browse/components/table-commons/HeadersRow.js
- src/components/browse/components/CustomColumnController.js
- src/components/browse/components/table-commons/HeadersRow.js
No branches depend on this, just minor improvement. Can be glanced-over/reviewed/merged whenever have free time.
> Rebuild tooltips when change hiddenColumns

- es/components/util/submission-view.js
- src/components/util/submission-view.js
Test with https://github.com/dbmi-bgm/cgap-portal/pull/339.
Changelog:
- Initialize zero values to zero instead of null in SubmissionView's BuildContext util (https://trello.com/c/6BWakdoQ/265-quick-edit-0-sometimes-shows-up-as-no-value-eg-loeuf)
> SV fix for initialize fields w/value = 0 to null

- es/components/browse/components/CustomColumnController.js
- es/components/browse/components/FacetList/FacetTermsList.js
- es/components/browse/components/FacetList/RangeFacet.js
- es/components/browse/components/FacetList/index.js
- es/components/forms/SubmissionView.js
- src/components/browse/components/CustomColumnController.js
- src/components/browse/components/FacetList/FacetTermsList.js
- src/components/browse/components/FacetList/RangeFacet.js
- src/components/browse/components/FacetList/index.js
- src/components/forms/SubmissionView.js
Cleanup
Minor update to CountIndicator (better determination of column idx when not 3 dots per column)
Bundled in fix for issue Will mentioned re: unsetting of FacetList Terms on /search/ and /browse/ views when click many (or single 1) rapidly. [Should now work like this](https://gyazo.com/a2e1aab36e2d27660c67ea8c34a2be8f).
Minor touchups done while working on FilterSetUI.
~~Despite the branch name, none of these are breaking changes nor does current FSUI (CGAP) PR depend on this. Can be merged whenever.~~
~~I take that back; added prop `ltr` to CountIndicator, which is used in CGAP FSUI now.~~
Nevermind again, `ltr` no longer used.
Most significant of these is auto-including institution and project in SubmissionView to allow creation to work. Not super pretty but it works.
> Touchups related to FSUI + (fix:) Unset filtering state on FacetLists Terms

- es/components/browse/components/table-commons/basicColumnExtensionMap.js
- src/components/browse/components/table-commons/basicColumnExtensionMap.js
**Changelog:**
- Bugfix for search table onclicks: give priority for navigation to href from `<a>` element (target or nearest parent) instead of always using item atID. 
- Uses atID as a fallback in the case no target or parent `<a>` is available
**Notes:**
- Necessary for full functionality of https://github.com/dbmi-bgm/cgap-portal/pull/345
- Seems like if multiple `<a>` tags are present (really shouldn't happen unless someone wraps the output of the column render function in a `<a>`), it'll use the innermost `<a>`'s href. Best way to avoid is to not do that, and instead pass link/href as a prop to the render f(x) instead.
> fix for displayTitle onclick: use href from a elem

- es/components/ui/ItemDetailList.js
- src/components/ui/ItemDetailList.js
Trello: https://trello.com/c/BbPD0VJm
For some cases, ItemDetailList displays object values as JSON text in table cells via calling `SubItemTable.jsonify(..)` function. (this is the fallback condition when a better choice not found) On the other hand, some objects are `Item` and could be rendered as links to Item pages instead of plain JSON text. This PR updates object handling.
release: https://github.com/4dn-dcic/shared-portal-components/tree/0.1.7b1
> Table Cells Not Correctly Rendered In Details Tab

- es/components/browse/EmbeddedSearchView.js
- es/components/browse/components/ControlsAndResults.js
- es/components/browse/components/SearchResultTable.js
- es/components/browse/components/table-commons/basicColumnExtensionMap.js
- src/components/browse/EmbeddedSearchView.js
- src/components/browse/components/ControlsAndResults.js
- src/components/browse/components/SearchResultTable.js
- src/components/browse/components/table-commons/basicColumnExtensionMap.js
Pls also check FF PR: https://github.com/4dn-dcic/fourfront/pull/1493
New `targetTabKey` prop (string) is added to embedded search tables. When a valid `targetTabKey` is passed, it is appended to result's `display_title` link's href with "#".
**Why do we need targetTabKey?**
When the user clicks the item link in the `display_title` column in the search results, it is navigated to the "Item" page with the default tab (1st tab) open. But we sometimes need to navigate to a specific tab. Here, `targetTabKey` helps us to navigate to the intended tab instead of the default.
Screencast (navigated to Exp.Set's Supplementary Files tab): https://i.gyazo.com/7f6f9d0146927bcffccb11a2423ee315.gif
> targetTabKey prop added to embedded search tables

- es/components/browse/components/CustomColumnController.js
- es/components/forms/components/Checkbox.js
- es/components/forms/components/IndeterminateCheckbox.js
- src/components/browse/components/CustomColumnController.js
- src/components/forms/components/Checkbox.js
- src/components/forms/components/IndeterminateCheckbox.js
Checkbox component (which provides label wrapper) now uses `IndeterminateCheckbox` instead of `<input type="checkbox">` JSX element if `props.indeterminate` is passed in and set to `true`.
> Support props.indeterminate in Checkbox

- es/components/util/layout.js
- src/components/util/layout.js
Please handle this PR along with https://github.com/4dn-dcic/fourfront/pull/1499
Trello: https://trello.com/c/Cypdy46K
Some lines of long descriptions are clipped off due to miscalculation of content height. This issue is observed in Chrome's desktop version and all mobile browsers.
Chrome has a known issue since version 47: https://stackoverflow.com/questions/65453475/getting-wrong-window-height-in-chrome
> Flexible Description Box Long Text Clipping Off Issue

- es/components/browse/components/StackedBlockTable.js
- es/components/util/analytics.js
- src/components/browse/components/StackedBlockTable.js
- src/components/util/analytics.js
Please handle this PR w/ https://github.com/4dn-dcic/fourfront/pull/1500
Trello: https://trello.com/c/oTpFC5hx
- Google Analytics lib does not respond well and makes the page crashing when there are too many files to be logged simultaneously. So we only track if the items are below a certain limit. (50)
- Instead of a collapsable panel that shows all items at once in stacked tables, we add an option to allow expanding the items in multiple steps. (https://t.gyazo.com/teams/ff-4dn/ab213aafe782e1536fa477c1cb0d7e3c.mp4) `incrementalExpandLimit` and `incrementalExpandStep` are introduced as new props.
> Performant Display of Stacked Tables Having Lots of Items

- es/components/browse/components/above-table-controls/AboveTableControlsBase.js
- es/components/browse/components/above-table-controls/RightButtonsSection.js
- package-lock.json
- src/components/browse/components/above-table-controls/AboveTableControlsBase.js
- src/components/browse/components/above-table-controls/RightButtonsSection.js
**Changelog**
- Adds a prop for hiding `MultiColumnSort` button in `AboveTableControlsBase`.
- Default behavior remains to show this by default, so shouldn't impact current implementations/usages of the component.
- Default value is specified in `RightButtonsSection`
- Some random package-lock updates that generated post-symlink
Relevant CGAP PR: https://github.com/dbmi-bgm/cgap-portal/pull/460
> Sv UI 2 - Allow hiding multicolumn sort in AboveTableControlsBase/RightButtonsSection

- es/components/browse/components/FacetList/FacetTermsList.js
- es/components/browse/components/FacetList/index.js
- src/components/browse/components/FacetList/FacetTermsList.js
- src/components/browse/components/FacetList/index.js
Trello: https://trello.com/c/sNhlMjbn
PS: Handle this PR with the [FF PR](https://github.com/4dn-dcic/fourfront/pull/1571) please.
The updates are mostly for the MicroMeta hardware summary table to display initial term selection as expanded. 
1. The current implementation takes window height and terms count into account to determine whether the facet is open. This feature remains as before, none of the browse/search pages are affected. We just extend it for `persistSelectedTerms` is `false` case that is currently default setting for MicroMeta hardware summary facets.
2. if `useRadioIcon` is `true` and all terms selected, we'll display `"+"`/`"-"` icon instead of `dot-circle`.
New: https://i.gyazo.com/b43d79bde6c1677cb624815bf439b457.gif
Old: …
> Default Open Facets Update

- es/components/forms/components/SearchAsYouTypeLocal.js
- src/components/forms/components/SearchAsYouTypeLocal.js
Changelog:
- Allow use of `optionalRenderFunction`, `titleRenderFunction` and `customFilterFunction` for `SearchAsYouTypeLocal`
- Needed for https://github.com/dbmi-bgm/cgap-portal/pull/571
> enable more customization for SAYT local

- es/components/ui/LocalizedTime.js
- src/components/ui/LocalizedTime.js
Small update to proptypes for LocalizedTime component, since some date-fns-tz methods actually accept more values than we're currently allowing in our code: https://github.com/marnusw/date-fns-tz#zonedtimetoutc.
Also fixes a proptype warning caused by this: https://github.com/dbmi-bgm/cgap-portal/pull/623
> Make LocalizedTime proptypes match date-fns-tz doc

- es/components/browse/SearchView.js
- es/components/browse/components/SelectedItemsController.js
- es/components/forms/components/LinkToSelector.js
- es/components/util/json-web-token.js
- es/components/util/misc.js
- package-lock.json
- package.json
- src/components/browse/SearchView.js
- src/components/browse/components/SelectedItemsController.js
- src/components/forms/components/LinkToSelector.js
- src/components/util/json-web-token.js
- src/components/util/misc.js
**Trello:** https://trello.com/c/dJCyoEJ0
Draft release: https://github.com/4dn-dcic/shared-portal-components/releases/tag/0.1.58b3
**Issues:**
Child popup windows are used for single or multiple item(s) selections in the data portal. One good example of selection would be adding files to the `HiGlassViewConfig`.
As is explained in detail in the Trello card, the initial page (SearchView) in the child window has a footer showing the count of the selected items along with Apply/Cancel buttons; but the footer disappears if you navigate to other pages. Since the child window lacks a top bar, you cannot quickly turn back to the initial page. (the only way is keyboard shortcuts or context menu)
Another issue is even if you manage to return to the selection page, you'll see that all previous …
> Child Popup Window Updates

- .gitignore
- LICENSE.txt
* Best practices is to have a `LICENSE.txt` with all of our repositories. I've added one here
* While I was here, I added some adjustments to `.gitignore` to know about a few more filenames.
> Add a LICENSE.txt

- es/components/browse/EmbeddedSearchView.js
- es/components/browse/SearchView.js
- es/components/browse/components/ControlsAndResults.js
- es/components/browse/components/FacetList/index.js
- package-lock.json
- package.json
- src/components/browse/EmbeddedSearchView.js
- src/components/browse/SearchView.js
- src/components/browse/components/ControlsAndResults.js
- src/components/browse/components/FacetList/index.js
1. **Trello:** https://trello.com/c/7JecO63N
`Background:` the simple representation of facet item in schema is like:
```json
"facets": {
"type": {
"title": "Data Type",
"description": "Some description of facet item"
"default_hidden": false // not required, boolean, the default value is false
"disabled": false // not required, boolean, the default value is false
"hide_from_view":  false // not required, boolean, the default value is false
}
},
```
Here, `default_hidden` and `disabled` work alike, where both are calculated by ES but not included in `context` returned to UI: https://github.com/4dn-dcic/snovault/blob/9af0fc33225dee56bf53ecb242e89c9150bccbf8/snovault/search/search.py#L634-L636
On the other hand, `hide_from_view` (introduced by AlexB but never actively used) is UI-oriented; …
> Add hide_from_view to Filter Facets

- es/components/static-pages/TableOfContents.js
- es/components/util/object.js
- package-lock.json
- package.json
- src/components/static-pages/TableOfContents.js
- src/components/util/object.js
- add `defaultExpanded` prop to display all items expanded in Table-of-Content
- add `whitespace` prop to make space between text and copy icon optional (default: true) in `CopyWrapper`.
> Minor Static Page Updates

- es/components/static-pages/StaticPageBase.js
- package-lock.json
- package.json
- src/components/static-pages/StaticPageBase.js
- `html-react-parser` npm package upgrade from v1 to v5
- updates relevant TOC components for `page.json` schema [change](https://github.com/4dn-dcic/fourfront/commit/c5f53b830f905818d527631230d8dae4ec326973)
> html-react-parser Upgrade and defaultExpanded Schema Updates

- es/components/browse/components/StackedBlockTable.js
- es/components/util/object.js
- package-lock.json
- package.json
- src/components/browse/components/StackedBlockTable.js
- src/components/util/object.js
Trello: https://trello.com/c/lRpSoh4o
`object.CopyWrapper` is currently sending analytics data into GA4 property. It includes copied value and it makes a security breach if sensitive data is wrapped. Two new props are added to improve security:
- `analyticsOnCopy: bool` // trigger analytics event (default is false)
- `maskAnalyticsValue: bool` // send the actual value (false) or send a placeholder instead (true - default)
> Improve object.CopyWrapper Security

- es/components/static-pages/TableOfContents.js
- package-lock.json
- package.json
- src/components/static-pages/TableOfContents.js
This fixes the "`props.children` used to be an array" assumption and converts non-array children to arrays before iterating through them.
> Bug Fix - Table of Content props.children handling

- es/components/ui/LocalizedTime.js
- package-lock.json
- package.json
- src/components/ui/LocalizedTime.js
Neutralize `date-fns'`s UTC adjustments for date time input lacks timezone.
For instance, if we have string literal `2025-01-01` as input and need to display it as `2025-01-01` using `LocalizedTime`, it is displayed as `2024-12-31` in GMT- time zones, whereas in GMT+ time zones it remains `2025-01-01`. Even though the represented datetime object is correct, the displayed date misleads users, particularly in facet date range components.
> LocalizedTime UTC Updates
