4dn-dcic/shared-portal-components

es/components/ui/ItemDetailList.js
src/components/ui/ItemDetailList.js

Items starting with`www.` (without any valid protocol, such as `http(s)://` ) will not be rendered as hyperlinks in item detail list anymore. (in other words, one of the previous commits is partly reverted)

Items starting with www. will not be rendered as hyperlinks

---

es/components/static-pages/BasicStaticSectionBody.js
src/components/static-pages/BasicStaticSectionBody.js

This PR is a part of https://github.com/4dn-dcic/fourfront/pull/1204

New Customizable Jsx Carousel Component

---

es/components/util/search-filters.js
src/components/util/search-filters.js

Pls handle this PR with https://github.com/4dn-dcic/fourfront/pull/1211

Fix Search Bar/QuickInfoBar Filter Issues + New Search Within Results Feature

---

es/components/browse/SearchView.js
es/components/browse/components/above-table-controls/AboveSearchViewTableControls.js
src/components/browse/SearchView.js
src/components/browse/components/above-table-controls/AboveSearchViewTableControls.js

This PR should be handled w/ https://github.com/4dn-dcic/fourfront/pull/1178/

Micrometa integration

---

es/components/forms/components/SearchAsYouTypeLocal.js
es/components/forms/components/SearchSelectionMenu.js
es/components/forms/components/submission-fields.js
scss/misc-ui-components.scss
src/components/forms/components/SearchAsYouTypeLocal.js
src/components/forms/components/SearchSelectionMenu.js
src/components/forms/components/submission-fields.js

Last-minute fixes for dropdown search as you type filtering

Quick fixes

---

es/components/browse/SearchView.js
es/components/browse/components/AboveSearchTablePanel.js
src/components/browse/SearchView.js
src/components/browse/components/AboveSearchTablePanel.js

Pls handle this PR w/ https://github.com/4dn-dcic/fourfront/pull/1228

Display Search Header Static Section: search-info-header.<Item type>

---

es/components/browse/components/StackedBlockTable.js
src/components/browse/components/StackedBlockTable.js

This PR should be handled w/ https://github.com/4dn-dcic/fourfront/pull/1243

Title Tooltip Added to QC Summary

---

es/components/browse/EmbeddedSearchView.js
es/components/browse/components/VirtualHrefController.js
src/components/browse/EmbeddedSearchView.js
src/components/browse/components/VirtualHrefController.js

`HideFacets` like new `HideColumns` prop introduced to hide columns if default columns will be displayed in `EmbeddedSearchView`.

HideColumns Prop Introduced to EmbeddedSearchView 

---

es/components/navigation/components/LoginController.js
es/components/ui/Alerts.js
src/components/navigation/components/LoginController.js
src/components/ui/Alerts.js

Currently this branch adds some minor improvements to Alerts, which requires small change in App.js of 4DN repo.
(Once that edit is done on 4DN, this branch will be safe to merge/apply; though not major issue if this is merged first).
Eventually this PR/branch may be expanded a little bit w. some other login-related edits (JWT storage).

Login Alert Things

---

es/components/forms/components/DragAndDropUpload.js
es/components/util/ajax.js
src/components/forms/components/DragAndDropUpload.js
src/components/util/ajax.js

Paired with fix for Pedigree Drag and Drop File Upload https://github.com/dbmi-bgm/cgap-portal/pull/236; also pre-req for cmphet update.
**To-Do**:

move promiseQueue to ajax util

---

es/components/ui/FileDownloadButton.js
src/components/ui/FileDownloadButton.js

Pls handle this PR w/ https://github.com/4dn-dcic/fourfront/pull/1405

Unauthenticated File Download Warnings

---

es/components/forms/components/SearchSelectionMenu.js
src/components/forms/components/SearchSelectionMenu.js

Trello ticket: https://trello.com/c/R4VOvNvX
**Solution:** a very minor update that removes redundant setState call in `componentDidUpdate` of `SearchSelectionMenu`

SubmissionView SAYTAjax Dropdown Closes on First Click

---

scss/search-view-table.scss

Straightforward minor CSS edit, should look like the following now -

SearchResultTable Edges: Heavily Increase box-shadow to indicate ability to horiz scroll more.

---

es/components/util/ajax.js
src/components/util/ajax.js

Add new ajaxsettings.onload(xhr) call to multipart form data function

Submit cgap fixes

---

es/components/browse/components/DetailPaneStateCache.js
es/components/browse/components/FacetList/RangeFacet.js
es/components/browse/components/SearchResultTable.js
es/components/browse/components/VirtualHrefController.js
es/components/browse/components/WindowNavigationController.js
es/components/ui/LocalizedTime.js
scss/facet-list.scss
src/components/browse/components/DetailPaneStateCache.js
src/components/browse/components/FacetList/RangeFacet.js
src/components/browse/components/SearchResultTable.js
src/components/browse/components/VirtualHrefController.js
src/components/browse/components/WindowNavigationController.js
src/components/ui/LocalizedTime.js

Pulls out some code from RangeFacets to make reusable for FilterSetUI -- https://github.com/dbmi-bgm/cgap-portal/pull/360.
Also minor touchups to existing code.

FilterSetUI + DetailPane related edits

---

es/components/ui/FileDownloadButton.js
src/components/ui/FileDownloadButton.js

Trello: https://trello.com/c/KXRBnuHW
This update is a part of https://github.com/4dn-dcic/fourfront/pull/1492
Release: https://github.com/4dn-dcic/shared-portal-components/releases/tag/0.1.8b1

Download Button Update For Xls/Xlsx Attachments

---

es/components/ui/ItemDetailList.js
es/components/util/misc.js
es/components/util/object.js
src/components/ui/ItemDetailList.js
src/components/util/misc.js
src/components/util/object.js

This PR solves the issues that explained in the tickets below:
1. 2D Array: https://trello.com/c/6CviAenq
2. Attachment: https://trello.com/c/dV3YiNdn
**SPC Release**: https://github.com/4dn-dcic/shared-portal-components/releases/tag/0.1.9b1
The existing implementation renders 2D arrays as a table which is hardly readable. Instead of a specific solution only for 2D arrays, a general approach that renders multi-dim arrays having items of primitive data types (https://developer.mozilla.org/en-US/docs/Glossary/Primitive) as a list of tuples is preferred.
**Old:** 
**New:**
Attachment links was not correctly rendered in tables, it is fixed.
**Old:**
**New:**

Item Details Updates for Multi-Dim Arrays and Attachments

---

es/components/forms/components/DragAndDropUpload.js
package-lock.json
src/components/forms/components/DragAndDropUpload.js

Updates for this PR: https://github.com/dbmi-bgm/cgap-portal/pull/419

Pedigree upload checkbox

---

es/components/browse/components/FacetList/RangeFacet.js
package-lock.json
src/components/browse/components/FacetList/RangeFacet.js

See Dana's comment on this ticket: https://trello.com/c/zzuMrRXC/401-add-support-for-no-value-bucket-to-rangefacet
Test with: https://github.com/dbmi-bgm/cgap-portal/pull/415/ (symlinked) OR https://github.com/dbmi-bgm/cgap-portal/pull/427

hide doc-counts

---

es/components/browse/components/SortController.js
package-lock.json
src/components/browse/components/SortController.js

**Trello:** https://trello.com/c/UBHYH2oQ
The multi-column sorting panel displays empty dropdowns when there are no results in search view.

Multi-column Sorting Panel Displays Empty Dropdowns

---

es/components/browse/components/SearchResultTable.js
package-lock.json
package.json
src/components/browse/components/SearchResultTable.js

Reverts 4dn-dcic/shared-portal-components#82

Revert "Integration of Forked/Updated React-17 Compatible react-infinite Package"

---

es/components/forms/components/SearchSelectionMenu.js
es/components/forms/components/VerticalScrollContainer.js
package-lock.json
package.json
src/components/forms/components/SearchSelectionMenu.js
src/components/forms/components/VerticalScrollContainer.js

**Changelog:**
- Some updates to accomodate update to react-bootstrap 1.6.4 in cgap-portal repo:
- Workaround fix for `SearchSelectionMenu`'s PopperJS margin warnings
- Fix for VerticalScrollContainer prop type warning
Goes with https://github.com/dbmi-bgm/cgap-portal/pull/593

April npm dep updates

---

es/components/util/logger.js
package-lock.json
package.json
src/components/util/logger.js

Trello: https://trello.com/c/MX7Bc8uT
pre-release: https://github.com/4dn-dcic/shared-portal-components/releases/tag/0.1.57b1

Sentry Sample Rate

---

package-lock.json
package.json

Trello: https://trello.com/c/zOayE7vY
- Upgrade @sentry/react to 7.35.0
- Upgrade @sentry/tracing to 7.35.0

Sentry React + Tracing Upgrades

---

es/components/browse/components/FacetList/index.js
es/components/browse/components/SearchResultTable.js
es/components/browse/components/VirtualHrefController.js
es/components/browse/components/table-commons/basicColumnExtensionMap.js
es/components/navigation/components/LoginController.js
es/components/ui/FileDownloadButton.js
es/components/util/analytics.js
es/components/util/object.js
package-lock.json
package.json
src/components/browse/components/FacetList/index.js
src/components/browse/components/SearchResultTable.js
src/components/browse/components/VirtualHrefController.js
src/components/browse/components/table-commons/basicColumnExtensionMap.js
src/components/navigation/components/LoginController.js
src/components/ui/FileDownloadButton.js
src/components/util/analytics.js
src/components/util/object.js

https://trello.com/c/LOfJamzG
FF PR: https://github.com/4dn-dcic/fourfront/pull/1819

UA to GA4 Migration

---

es/components/util/analytics.js
package-lock.json
package.json
src/components/util/analytics.js

Trello: https://trello.com/c/yh0RkuqJ

GA4 - Item Click Events

---

es/components/browse/components/FacetList/index.js
es/components/forms/components/DragAndDropUpload.js
es/components/forms/components/Toggle.js
es/components/static-pages/StaticPageBase.js
es/components/static-pages/TableOfContents.js
es/components/ui/FontAwesomeV6Icons.js
es/components/ui/ItemDetailList.js
es/components/util/object.js
package-lock.json
package.json
scss/facet-list.scss
scss/toggle-switch.scss
src/components/browse/components/FacetList/index.js
src/components/forms/components/Toggle.js
src/components/static-pages/StaticPageBase.js
src/components/static-pages/TableOfContents.js
src/components/ui/FontAwesomeV6Icons.js
src/components/ui/ItemDetailList.js
src/components/util/object.js

This branch is a combination of branches [smaht-ui-updates](https://github.com/4dn-dcic/shared-portal-components/compare/smaht-ui-updates), [cfm-qc_fix](https://github.com/4dn-dcic/shared-portal-components/compare/cfm-qc_fix), and [cfm-facet_styles](https://github.com/4dn-dcic/shared-portal-components/compare/cfm-facet_styles).

Cfm QC and facet updates

---

es/components/browse/components/table-commons/HeadersRow.js
es/components/forms/components/DragAndDropUpload.js
es/components/static-pages/TableOfContents.js
package-lock.json
package.json
src/components/browse/components/table-commons/HeadersRow.js

- Fix for broken/unused `hideTooltip`
https://github.com/4dn-dcic/shared-portal-components/releases/tag/0.1.76b1
https://github.com/smaht-dac/smaht-portal/pull/45

Bm tooltiptip fix

---

es/components/ui/DotRouter.js
es/components/ui/YoutubeVideoEmbed.js
src/components/ui/DotRouter.js
src/components/ui/YoutubeVideoEmbed.js

Corresponds to [Trello Ticket 913](https://trello.com/c/ZulZ3kaj/913-dotrouter-transfer).
- Transfer the DotRouter and YoutubeVideoEmbed component out of the CGAP portal into this repository
- Will facilitate tab-navigation in the new SMaHT File Overview page
Note: Merging this into a larger PR

CGAP Components Transfer

---

es/components/browse/components/table-commons/basicColumnExtensionMap.js
es/components/ui/LocalizedTime.js
package-lock.json
package.json
src/components/browse/components/table-commons/basicColumnExtensionMap.js
src/components/ui/LocalizedTime.js

Trello: https://trello.com/c/BsmhPhCF
`<LocalizedTime />` component cannot handle invalid dates and makes UI fail completely.

Bug Fix - LocalizedTime

---

es/components/util/analytics.js
package-lock.json
package.json
src/components/util/analytics.js

Trello: https://trello.com/c/39rBss0A

Fix Analytics Impressions for 200+ Items

---

es/components/browse/components/above-table-controls/AboveSearchViewTableControls.js
es/components/browse/components/above-table-controls/AboveTableControlsBase.js
package-lock.json
package.json
src/components/browse/components/above-table-controls/AboveSearchViewTableControls.js
src/components/browse/components/above-table-controls/AboveTableControlsBase.js

Adds `customizationButtonClassName` prop to set customColumns and multiColumnSort button styles in AboveTableControlsBase component specifically used for search view..

customizationButtonClassName prop
